#!/bin/bash
pokemon=("bulbasaur" "ivysaur" "venusaur" "charmander" "charmeleon")

exec 2>> errors.txt

for item in "${pokemon[@]}"; do

  echo Fetching data for $item...

  for i in {1..3}; do
    curl -f https://pokeapi.co/api/v2/pokemon/$item > $item.json
    echo "Attempt $i for $item failed. Retrying..." >&2

    sleep 1
  done

  echo "Saved data to $item.json ✅"
  sleep 1

done
