#!/bin/bash

jq -r ' 
  . as $root | 
  ($root.forms[0].name | ascii_upcase[0:1] + .[1:]) as $name | 
  ($root.types[0].type.name | ascii_upcase[0:1] + .[1:]) as $type | 
  ($root.weight / 10) as $weight | ($root.height / 10) as $height | 
  "\($name) is of type \($type), weighs \($weight)kg, and is \($height) tall." 
' data.json



# Pikachu is of type Electric, weighs 6kg, and is 0.4m tall
